import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "../components/ThemeProvider";
import { getServerSession } from "next-auth/next";
import { authOptions } from "../lib/auth";
import { Inter } from "next/font/google";
import LayoutContent from "../components/LayoutContent";
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased`}
      >
        <Providers>
          <LayoutContent session={session}>
            {children}
          </LayoutContent>
        </Providers>
      </body>
    </html>
  );
}
