// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import { Providers } from "../components/ThemeProvider";
import { getServerSession } from "next-auth/next";
import { authOptions } from "../lib/auth";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased`}
      >
        <Providers>
          {session ? (
            <div className="flex h-screen">
              <Sidebar />
              <div className="flex flex-col flex-1">
                <Navbar />
                <main className="flex-1 overflow-y-auto p-6">{children}</main>
              </div>
            </div>
          ) : (
            <div className="min-h-screen">{children}</div>
          )}
        </Providers>
      </body>
    </html>
  );
}
